#!/usr/bin/env python3
"""Generate XOR-obfuscated Tidal client credentials for embedding.

Usage:
    python3 scripts/gen_embedded.py CLIENT_ID CLIENT_SECRET > src/tidal/embedded.rs

The ciphertext and the key both ship in the binary. This is obfuscation,
not encryption. It only stops casual string scanning.
"""
import os
import sys


def xor(data: bytes, key: bytes) -> bytes:
    return bytes(a ^ b for a, b in zip(data, key))


def fmt(bs: bytes) -> str:
    return ", ".join(f"0x{b:02x}" for b in bs)


def main() -> None:
    if len(sys.argv) != 3:
        print(__doc__)
        sys.exit(1)

    cid = sys.argv[1].encode()
    secret = sys.argv[2].encode()
    key_id = os.urandom(len(cid))
    key_secret = os.urandom(len(secret))
    enc_id = xor(cid, key_id)
    enc_secret = xor(secret, key_secret)

    print("// Auto-generated by scripts/gen_embedded.py. Do not edit by hand.")
    print(f"const ENC_ID: [u8; {len(enc_id)}] = [ {fmt(enc_id)} ];")
    print(f"const KEY_ID: [u8; {len(key_id)}] = [ {fmt(key_id)} ];")
    print(f"const ENC_SECRET: [u8; {len(enc_secret)}] = [ {fmt(enc_secret)} ];")
    print(f"const KEY_SECRET: [u8; {len(key_secret)}] = [ {fmt(key_secret)} ];")
    print(
        """
fn decode(enc: &[u8], key: &[u8]) -> String {
    enc.iter().zip(key).map(|(a, b)| (a ^ b) as char).collect()
}

pub fn client_id() -> String {
    decode(&ENC_ID, &KEY_ID)
}

pub fn client_secret() -> String {
    decode(&ENC_SECRET, &KEY_SECRET)
}
"""
    )


if __name__ == "__main__":
    main()
